### ISSUE TITLE
FileNotFoundError: [Errno 2] 'Plots/CashFlowsChart.png'

### ISSUE THREAD

**Issue by timojuez** [roisol144/Stocks-Intrinsic-Value#2]
```Traceback (most recent call last):
  File "stockValue.py", line 58, in <module>
    plt.savefig('Plots/CashFlowsChart.png')
  File "/home/timo/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/timo/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/timo/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/timo/.local/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3agg.py", line 76, in print_png
    return agg.print_png(filename, *args, **kwargs)
  File "/home/timo/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/timo/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "/home/timo/.local/lib/python3.8/site-packages/matplotlib/image.py", line 1605, in imsave
    image.save(fname, **pil_kwargs)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2099, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: 'Plots/CashFlowsChart.png'
```
The exception is being raised when the directory `Plots` does not exist. The script should create it automatically, e.g.
```
import os
try:
  os.mkdir("Plots")
except: pass
```

**Comment by hpicsk** [comment]
make dir names 'Plots'
